### ISSUE TITLE
subtree, stages names and colors in plot 

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#38]
It works only if specified col = "stages" as option in the plot function. Generalize it also for the code reported below, for example.

_m0 <- staged_ev_tree(chds, fit = TRUE, full = TRUE)
naiv <- naive.sevt(m0)
plot(naiv, cex.label.edges = 0.5, cex.nodes = 3, pch = 16)
sub_naiv <- subtree.sevt(naiv, path = c("High", "Low"))
plot(sub_naiv, cex.label.edges = 0.5, cex.nodes = 3, pch = 16)_

**Comment by gherardovarando** [comment]
working code:

```
data (Titanic)
m0 <- staged_ev_tree(Titanic, fit = TRUE, full = TRUE, lambda = 1)
naiv <- naive.sevt(m0)
plot(naiv, cex.label.edges = 0.5, cex.nodes = 3, pch = 16, col = "stages")
sub_naiv <- subtree.sevt(naiv, path = c("Crew", "Male"))
plot(sub_naiv, cex.label.edges = 0.5, cex.nodes = 3, pch = 16, col = "stages")
```

Problem with colour of first variable.

**Comment by gherardovarando** [comment]
Now it should work, I had to change a bit some other functions, essentially now we can also indicates a stage for the first variable (useless for the model, but useful to plot a subtree).
Since now the `stages` field in the `sevt` object can be of length equal to `length($tree)` or `length($tree) - 1` we must be careful in other functions. 
More testing is needed to check if this change did not introduce some other bugs.
