### ISSUE TITLE
predict.sevt

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#56]
m0 <- full(PhDArticles, lambda = 0)
p1 <- predict(m0, newdata = expand.grid(m0$tree), prob = T)
p1
p2 <- predict(m0, newdata = expand.grid(m0$tree), prob = F)
p2

It has 36 values with NA in p1 or factor(0) in p2.
The problem is that we have 18 situations with NaN distribution on the last level of the tree (m0$prob$Prestige).

(With lambda > 0 it works).

**Comment by gherardovarando** [comment]
I think it is not a bug, if `lambda = 0` the model can not predict unseen cases since the conditional probabilities for those events are not well defined. 
Setting `lambda = 0` is almost compulsory when using a model as a classifier. 

Anyway the user can interpret `factor(0` as "the model has no clue what to predict"

**Comment by FedericoCarli** [comment]
ok I am agree with that interpretation. Maybe we can put a comment as the one you did in the documentation/help page of predict function..
